### ISSUE TITLE
Add README.md file 

### ISSUE THREAD

**Issue by ankman007** [ankman007/YouTube-Clone#1]
### Description
Currently this repo doesn't have a descriptive README.md file. You will need to add all other necessary details missing to the file such as getting started section, screenshots of the project, guidelines for contributions section and so on. Make sure to follow guides to creating a good README.md file.

**Comment by AhsanCommits** [comment]
I'm confident that I can contribute to this. Could you please assign it to me?

**Comment by ankman007** [comment]
> I'm confident that I can contribute to this. Could you please assign it to me?

Done. Good Luck.
