### ISSUE TITLE
Extra Space Appearing in Buttons. 

### ISSUE THREAD

**Issue by adcs1** [ankman007/YouTube-Clone#5]
Description:   Extra Space Appearing Beneath Text in Buttons.

Expected: Extra Space Should be Removed.

Actual: Extra Space Appearing.
![image](https://github.com/ankman007/YouTube-Clone/assets/88266244/2b028dd2-f685-4712-9dc6-641b714123c4)

**Comment by SUBS2905** [comment]
Hi there, I would like to work on this issue. Can you assign it to me?

**Comment by SUBS2905** [comment]
Hi there, I'm interested to work on this issue. Please assign this to me.
